### ISSUE TITLE
Add line breaks to formatting

### ISSUE THREAD

**Issue by Loggy98** [rotgruengelb/your_time#5]
My current setup is "%tH% Hours Played", but I would like to add (%d% Days). But it takes up just a bit too much space horizontally on the screen, and it would great if we could specify line breaks to put more detailed info below.

For example, it would currently look like this:

1127 Hours Played (46 Days)

But with a line break inserted in the formatting, it could look like this:

1127 Hours Played
(46 Days)

**Comment by rotgruengelb** [comment]
Thank you for the suggestion. I see the appeal and will look into it.

**Comment by rotgruengelb** [comment]
Got the functionality done. Will release some time Today/Tomorrow for 1.21

**Comment by rotgruengelb** [comment]
![grafik](https://github.com/rotgruengelb/your_time/assets/75038404/1d5d3337-e104-454c-98a9-a9db9feddef0)
![grafik](https://github.com/rotgruengelb/your_time/assets/75038404/06d1cfe1-f42d-4e8d-acbc-293e8d0c1344)

**Comment by rotgruengelb** [comment]
https://modrinth.com/mod/your_time/version/0.0.5+1.21
https://modrinth.com/mod/your_time/version/0.0.5+1.20.6
