### ISSUE TITLE
1.21 Crash when joining world (with other mods?)

### ISSUE THREAD

**Issue by StaxPy** [rotgruengelb/your_time#7]
[Crash report](https://mclo.gs/u15j6nh)

Works fine when testing in IntelliJ, but crashes in my modpack.

**Comment by rotgruengelb** [comment]
This is due to an incompatibility between the newest Nixenaut Version and the newest Your_Time version. This does not occur in a dev environment, as it automatically downloads the correct version.

Working on a patch.

**Comment by rotgruengelb** [comment]
Can you try the artifact produced [here](https://github.com/rotgruengelb/your_time/actions/runs/10819490739) with the newest version of Nixienaut?

**Comment by rotgruengelb** [comment]
Fix will be merged into 1.21 branch and later older versions too.
